services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: home_expenses
    volumes:
      - ./data:/var/lib/postgresql/data 
    ports:
      - ${DB_PORT}:${DB_PORT}